# nvfetcher.toml
[zeek-latest]
src.git = "https://github.com/zeek/zeek"
fetch.github = "zeek/zeek"
git.fetchSubmodules = true

# [vast-broker]
# src.manual= "v1.4.0"
# fetch.github = "zeek/broker"
# git.fetchSubmodules = true

[zeek-release]
src.github = "zeek/zeek"
fetch.url = "https://github.com/zeek/zeek/releases/download/v$ver/zeek-$ver.tar.gz"
src.prefix = "v"

[zeek-plugin-pdf]
src.git = "https://github.com/reservoirlabs/zeek-pdf-analyzer"
fetch.github = "reservoirlabs/zeek-pdf-analyzer"

[zeek-plugin-zip]
src.git = "https://github.com/reservoirlabs/zeek-zip-analyzer"
fetch.github = "reservoirlabs/zeek-zip-analyzer"

[zeek-plugin-ikev2]
src.git = "https://github.com/ukncsc/zeek-ikev2"
fetch.github = "ukncsc/zeek-ikev2"


[zeek-plugin-postgresql]
src.git = "https://github.com/0xxon/zeek-postgresql"
fetch.github = "0xxon/zeek-postgresql"

[zeek-plugin-http2]
src.git = "https://github.com/MITRECND/bro-http2"
fetch.github = "MITRECND/bro-http2"


[zeek-plugin-community-id]
src.git = "https://github.com/corelight/zeek-community-id"
fetch.github = "corelight/zeek-community-id"


[icsnpp-bacnet]
src.git = "https://github.com/cisagov/icsnpp-bacnet"
fetch.github = "cisagov/icsnpp-bacnet"


[zeek-plugin-kafka]
src.git = "https://github.com/SeisoLLC/zeek-kafka"
fetch.github = "SeisoLLC/zeek-kafka"


[spicy-analyzers]
src.git = "https://github.com/zeek/spicy-analyzers"
fetch.github = "zeek/spicy-analyzers"
