# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl }:
{
  spicy = {
    pname = "spicy";
    version = "8fdeb3be1965cf31badac68dd0031416dfe1dca3";
    src = fetchgit {
      url = "https://github.com/zeek/spicy";
      rev = "8fdeb3be1965cf31badac68dd0031416dfe1dca3";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "1175jz3v6cbq4qb2apqdbksz9x1iknidwg1sab35d3lrchlay0iw";
    };

  };
  zeek-master = {
    pname = "zeek-master";
    version = "b04c611058216060365c270f955b26c1f5f3e1cf";
    src = fetchgit {
      url = "https://github.com/zeek/zeek";
      rev = "b04c611058216060365c270f955b26c1f5f3e1cf";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "0gxdx7idpili9gssva3v1vs7za35gaa7sqycbk9bxgcmijv88rg5";
    };

  };
  zeek-release = {
    pname = "zeek-release";
    version = "4.0.2";
    src = fetchurl {
      sha256 = "15gxxgg7nmfmswlbxhvcp6alq5k9wpvrm5cwyf1qfd7xsfli61sm";
      url = "https://github.com/zeek/zeek/releases/download/v4.0.2/zeek-4.0.2.tar.gz";
    };

  };
}
