# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  icsnpp-bacnet = {
    pname = "icsnpp-bacnet";
    version = "35243a1a3e821216df693761bc67ef1b7f3203f5";
    src = fetchFromGitHub ({
      owner = "cisagov";
      repo = "icsnpp-bacnet";
      rev = "35243a1a3e821216df693761bc67ef1b7f3203f5";
      fetchSubmodules = false;
      sha256 = "sha256-/Tm1XAVO+SonIDnM6Tafq9iiGJ+YB0wnqebTdpnbM6I=";
    });
  };
  zeek-agent = {
    pname = "zeek-agent";
    version = "c67772b3acbeb1b5d3d74349aee9e6a8521da983";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek-agent";
      rev = "c67772b3acbeb1b5d3d74349aee9e6a8521da983";
      fetchSubmodules = true;
      sha256 = "sha256-gqGt4yDLkU3J8vm8Gxroz1VUfssFsJJOaAScSUsEvic=";
    });
  };
  zeek-latest = {
    pname = "zeek-latest";
    version = "d957f883df242ef159cfd846884e673addeea7a5";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek";
      rev = "d957f883df242ef159cfd846884e673addeea7a5";
      fetchSubmodules = true;
      sha256 = "sha256-14hHGyNzHKc0/Wco8juHYeg3MCE/YOmEVABK5VisB2w=";
    });
  };
  zeek-plugin-af_packet = {
    pname = "zeek-plugin-af_packet";
    version = "a2872e8f5eb7d4f8d365c373369c98e4814b3344";
    src = fetchFromGitHub ({
      owner = "J-Gras";
      repo = "zeek-af_packet-plugin";
      rev = "a2872e8f5eb7d4f8d365c373369c98e4814b3344";
      fetchSubmodules = false;
      sha256 = "sha256-oiwHw4e20PahAVB41vJQ/aLj8CIB6cKNHo7PPqJJE7s=";
    });
  };
  zeek-plugin-community-id = {
    pname = "zeek-plugin-community-id";
    version = "ea6df2b8c9c2fbb62cba8dba88d48a5c6a83e83a";
    src = fetchFromGitHub ({
      owner = "corelight";
      repo = "zeek-community-id";
      rev = "ea6df2b8c9c2fbb62cba8dba88d48a5c6a83e83a";
      fetchSubmodules = false;
      sha256 = "sha256-UDU6vGrpxwqtXd36oUhUKdGAV5c9LKpvoB/rcN/ICXY=";
    });
  };
  zeek-plugin-http2 = {
    pname = "zeek-plugin-http2";
    version = "7dc14042d1602065d60601d193b99b005f08fe34";
    src = fetchFromGitHub ({
      owner = "MITRECND";
      repo = "bro-http2";
      rev = "7dc14042d1602065d60601d193b99b005f08fe34";
      fetchSubmodules = false;
      sha256 = "sha256-EbO6WV1fcFtHRSaFkd/pPPNjMYkDeeZtn8KZHM3gug8=";
    });
  };
  zeek-plugin-ikev2 = {
    pname = "zeek-plugin-ikev2";
    version = "5b62d506573da388bb4df0446cc87cdffc12a438";
    src = fetchFromGitHub ({
      owner = "ukncsc";
      repo = "zeek-ikev2";
      rev = "5b62d506573da388bb4df0446cc87cdffc12a438";
      fetchSubmodules = false;
      sha256 = "sha256-ct1nQcbDGQ2V9lrKD/snhmF3EEkDXCbQfiJpSwOmKPI=";
    });
  };
  zeek-plugin-kafka = {
    pname = "zeek-plugin-kafka";
    version = "b632187c7afdc75365a256a7d9bb2e5cc81ab46f";
    src = fetchFromGitHub ({
      owner = "SeisoLLC";
      repo = "zeek-kafka";
      rev = "b632187c7afdc75365a256a7d9bb2e5cc81ab46f";
      fetchSubmodules = false;
      sha256 = "sha256-CJXnPam24gPx7Jd4CZJRsdUh7e4H5P7gaf/v2Q4xZ60=";
    });
  };
  zeek-plugin-postgresql = {
    pname = "zeek-plugin-postgresql";
    version = "b2b70900a3b4779efbcb9a39eae8cab1d714f97f";
    src = fetchFromGitHub ({
      owner = "0xxon";
      repo = "zeek-postgresql";
      rev = "b2b70900a3b4779efbcb9a39eae8cab1d714f97f";
      fetchSubmodules = false;
      sha256 = "sha256-O2yWL2Ippv5GFxSesv7Eclw78p2YnT3UWnZ8W54NMdc=";
    });
  };
  zeek-plugin-spicy = {
    pname = "zeek-plugin-spicy";
    version = "ebaa2b20233a79171f603175aa08132f527adfde";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "spicy-plugin";
      rev = "ebaa2b20233a79171f603175aa08132f527adfde";
      fetchSubmodules = false;
      sha256 = "sha256-8/ofTzGNR4QbIGMkEtwn56q1xEBWqjEDr24FRvB5f14=";
    });
  };
  zeek-release = {
    pname = "zeek-release";
    version = "4.2.2";
    src = fetchurl {
      url = "https://github.com/zeek/zeek/releases/download/v4.2.2/zeek-4.2.2.tar.gz";
      sha256 = "sha256-9Q3X24uAmnSnLUAklK+gC0Mu8eh81ZE2h/7uIVc8cAw=";
    };
  };
  zeek-tls = {
    pname = "zeek-tls";
    version = "5.0.0";
    src = fetchurl {
      url = "https://github.com/zeek/zeek/archive/refs/tags/v5.0.0.tar.gz";
      sha256 = "sha256-UxSVgzp6QwIgMa4oY/RY0SQrPUdLrgc/it+ntvobjX0=";
    };
  };
}
