# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  icsnpp-bacnet = {
    pname = "icsnpp-bacnet";
    version = "35243a1a3e821216df693761bc67ef1b7f3203f5";
    src = fetchFromGitHub ({
      owner = "cisagov";
      repo = "icsnpp-bacnet";
      rev = "35243a1a3e821216df693761bc67ef1b7f3203f5";
      fetchSubmodules = false;
      sha256 = "sha256-/Tm1XAVO+SonIDnM6Tafq9iiGJ+YB0wnqebTdpnbM6I=";
    });
  };
  netmap = {
    pname = "netmap";
    version = "6546c5c732082991ea357643b6a36100e3b16885";
    src = fetchFromGitHub ({
      owner = "luigirizzo";
      repo = "netmap";
      rev = "6546c5c732082991ea357643b6a36100e3b16885";
      fetchSubmodules = false;
      sha256 = "sha256-k0/L7ZiPGhC1nH7CPiBlwyepepcj7QH5BxP+wi4bOUE=";
    });
  };
  zeek-agent = {
    pname = "zeek-agent";
    version = "c67772b3acbeb1b5d3d74349aee9e6a8521da983";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek-agent";
      rev = "c67772b3acbeb1b5d3d74349aee9e6a8521da983";
      fetchSubmodules = true;
      sha256 = "sha256-gqGt4yDLkU3J8vm8Gxroz1VUfssFsJJOaAScSUsEvic=";
    });
  };
  zeek-latest = {
    pname = "zeek-latest";
    version = "8a4ed58731e51f5557fb8c08e9cd7b77720e7bcf";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek";
      rev = "8a4ed58731e51f5557fb8c08e9cd7b77720e7bcf";
      fetchSubmodules = true;
      sha256 = "sha256-FQrNcCwGg8BBhfRrfOD626wpJbIgAxeOf5IOTVBEJVM=";
    });
  };
  zeek-netmap = {
    pname = "zeek-netmap";
    version = "9a4d77d0ecd71c72b4e27579dc68c753139ae2c8";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek-netmap";
      rev = "9a4d77d0ecd71c72b4e27579dc68c753139ae2c8";
      fetchSubmodules = false;
      sha256 = "sha256-yObo/IFaPVwSkprCjL1ehjU3HS+PqmjN2cuXf6bQDl4=";
    });
  };
  zeek-plugin-af_packet = {
    pname = "zeek-plugin-af_packet";
    version = "a2872e8f5eb7d4f8d365c373369c98e4814b3344";
    src = fetchFromGitHub ({
      owner = "J-Gras";
      repo = "zeek-af_packet-plugin";
      rev = "a2872e8f5eb7d4f8d365c373369c98e4814b3344";
      fetchSubmodules = false;
      sha256 = "sha256-oiwHw4e20PahAVB41vJQ/aLj8CIB6cKNHo7PPqJJE7s=";
    });
  };
  zeek-plugin-community-id = {
    pname = "zeek-plugin-community-id";
    version = "ea6df2b8c9c2fbb62cba8dba88d48a5c6a83e83a";
    src = fetchFromGitHub ({
      owner = "corelight";
      repo = "zeek-community-id";
      rev = "ea6df2b8c9c2fbb62cba8dba88d48a5c6a83e83a";
      fetchSubmodules = false;
      sha256 = "sha256-UDU6vGrpxwqtXd36oUhUKdGAV5c9LKpvoB/rcN/ICXY=";
    });
  };
  zeek-plugin-http2 = {
    pname = "zeek-plugin-http2";
    version = "7dc14042d1602065d60601d193b99b005f08fe34";
    src = fetchFromGitHub ({
      owner = "MITRECND";
      repo = "bro-http2";
      rev = "7dc14042d1602065d60601d193b99b005f08fe34";
      fetchSubmodules = false;
      sha256 = "sha256-EbO6WV1fcFtHRSaFkd/pPPNjMYkDeeZtn8KZHM3gug8=";
    });
  };
  zeek-plugin-ikev2 = {
    pname = "zeek-plugin-ikev2";
    version = "5b62d506573da388bb4df0446cc87cdffc12a438";
    src = fetchFromGitHub ({
      owner = "ukncsc";
      repo = "zeek-ikev2";
      rev = "5b62d506573da388bb4df0446cc87cdffc12a438";
      fetchSubmodules = false;
      sha256 = "sha256-ct1nQcbDGQ2V9lrKD/snhmF3EEkDXCbQfiJpSwOmKPI=";
    });
  };
  zeek-plugin-kafka = {
    pname = "zeek-plugin-kafka";
    version = "b632187c7afdc75365a256a7d9bb2e5cc81ab46f";
    src = fetchFromGitHub ({
      owner = "SeisoLLC";
      repo = "zeek-kafka";
      rev = "b632187c7afdc75365a256a7d9bb2e5cc81ab46f";
      fetchSubmodules = false;
      sha256 = "sha256-CJXnPam24gPx7Jd4CZJRsdUh7e4H5P7gaf/v2Q4xZ60=";
    });
  };
  zeek-plugin-postgresql = {
    pname = "zeek-plugin-postgresql";
    version = "b2b70900a3b4779efbcb9a39eae8cab1d714f97f";
    src = fetchFromGitHub ({
      owner = "0xxon";
      repo = "zeek-postgresql";
      rev = "b2b70900a3b4779efbcb9a39eae8cab1d714f97f";
      fetchSubmodules = false;
      sha256 = "sha256-O2yWL2Ippv5GFxSesv7Eclw78p2YnT3UWnZ8W54NMdc=";
    });
  };
  zeek-plugin-spicy = {
    pname = "zeek-plugin-spicy";
    version = "bca0ba5e1f89dcd30f98cc0be8178308dc952bb9";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "spicy-plugin";
      rev = "bca0ba5e1f89dcd30f98cc0be8178308dc952bb9";
      fetchSubmodules = false;
      sha256 = "sha256-D7VP1S0hZtDIoYur/a/mujmEnkbXrjOaWw3yLsHl1JY=";
    });
  };
  zeek-release = {
    pname = "zeek-release";
    version = "5.0.0";
    src = fetchurl {
      url = "https://github.com/zeek/zeek/releases/download/v5.0.0/zeek-5.0.0.tar.gz";
      sha256 = "sha256-0NMA/Y2aGkhaAZjFLpdz23xTKCD6rqeX5MY6r6xj/X4=";
    };
  };
  zeek-tls = {
    pname = "zeek-tls";
    version = "5.0.0";
    src = fetchurl {
      url = "https://github.com/zeek/zeek/archive/refs/tags/v5.0.0.tar.gz";
      sha256 = "sha256-UxSVgzp6QwIgMa4oY/RY0SQrPUdLrgc/it+ntvobjX0=";
    };
  };
}
