# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  icsnpp-bacnet = {
    pname = "icsnpp-bacnet";
    version = "43c7b892c4f271f398feb406184473b432c45bb2";
    src = fetchFromGitHub ({
      owner = "cisagov";
      repo = "icsnpp-bacnet";
      rev = "43c7b892c4f271f398feb406184473b432c45bb2";
      fetchSubmodules = false;
      sha256 = "sha256-B0Z+3HMKCzRiIZF0Zs8U0GTacAgSmVSUaUNAqGD3Fg0=";
    });
    date = "2022-11-10";
  };
  netmap = {
    pname = "netmap";
    version = "d67a604e805b67efb563ea8d5eb2d1318acf6ed8";
    src = fetchFromGitHub ({
      owner = "luigirizzo";
      repo = "netmap";
      rev = "d67a604e805b67efb563ea8d5eb2d1318acf6ed8";
      fetchSubmodules = false;
      sha256 = "sha256-kqQNCx0a3ZU6wlgmPze7YxT/0cysHkpEQtbul8tehyo=";
    });
    date = "2022-10-25";
  };
  zeek-af_packet = {
    pname = "zeek-af_packet";
    version = "201480f59421378b433688927d1fb73c6699cac4";
    src = fetchFromGitHub ({
      owner = "J-Gras";
      repo = "zeek-af_packet-plugin";
      rev = "201480f59421378b433688927d1fb73c6699cac4";
      fetchSubmodules = false;
      sha256 = "sha256-HOEAMWyXebCvGUQdQiboUSBn9TMR2yq2NB6qtl9gVRI=";
    });
    date = "2022-10-29";
  };
  zeek-agent = {
    pname = "zeek-agent";
    version = "c67772b3acbeb1b5d3d74349aee9e6a8521da983";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek-agent";
      rev = "c67772b3acbeb1b5d3d74349aee9e6a8521da983";
      fetchSubmodules = true;
      sha256 = "sha256-gqGt4yDLkU3J8vm8Gxroz1VUfssFsJJOaAScSUsEvic=";
    });
    date = "2020-11-19";
  };
  zeek-community-id = {
    pname = "zeek-community-id";
    version = "424a13eebf5efcc91dd77a9c5f762297fc2bba39";
    src = fetchFromGitHub ({
      owner = "corelight";
      repo = "zeek-community-id";
      rev = "424a13eebf5efcc91dd77a9c5f762297fc2bba39";
      fetchSubmodules = false;
      sha256 = "sha256-YDqeva8xkIj1emaqwh7Rohi6u5G3NuJfUW52iH9phTs=";
    });
    date = "2022-07-16";
  };
  zeek-dpdk = {
    pname = "zeek-dpdk";
    version = "c22ea7e2fd59bc03c646970f6fb3da10d43585a8";
    src = fetchFromGitHub ({
      owner = "esnet";
      repo = "dpdk-plugin";
      rev = "c22ea7e2fd59bc03c646970f6fb3da10d43585a8";
      fetchSubmodules = false;
      sha256 = "sha256-42KFlcSjaZea7faPeP3HpndVSoDMAGjlrsPSVyj4TYc=";
    });
    date = "2022-11-15";
  };
  zeek-http2 = {
    pname = "zeek-http2";
    version = "7dc14042d1602065d60601d193b99b005f08fe34";
    src = fetchFromGitHub ({
      owner = "MITRECND";
      repo = "bro-http2";
      rev = "7dc14042d1602065d60601d193b99b005f08fe34";
      fetchSubmodules = false;
      sha256 = "sha256-EbO6WV1fcFtHRSaFkd/pPPNjMYkDeeZtn8KZHM3gug8=";
    });
    date = "2021-10-06";
  };
  zeek-ikev2 = {
    pname = "zeek-ikev2";
    version = "5b62d506573da388bb4df0446cc87cdffc12a438";
    src = fetchFromGitHub ({
      owner = "ukncsc";
      repo = "zeek-ikev2";
      rev = "5b62d506573da388bb4df0446cc87cdffc12a438";
      fetchSubmodules = false;
      sha256 = "sha256-ct1nQcbDGQ2V9lrKD/snhmF3EEkDXCbQfiJpSwOmKPI=";
    });
    date = "2020-01-27";
  };
  zeek-kafka = {
    pname = "zeek-kafka";
    version = "b632187c7afdc75365a256a7d9bb2e5cc81ab46f";
    src = fetchFromGitHub ({
      owner = "SeisoLLC";
      repo = "zeek-kafka";
      rev = "b632187c7afdc75365a256a7d9bb2e5cc81ab46f";
      fetchSubmodules = false;
      sha256 = "sha256-CJXnPam24gPx7Jd4CZJRsdUh7e4H5P7gaf/v2Q4xZ60=";
    });
    date = "2022-06-30";
  };
  zeek-latest = {
    pname = "zeek-latest";
    version = "0e97c29eb83681740bc6569c1346bf0fb6b0c800";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek";
      rev = "0e97c29eb83681740bc6569c1346bf0fb6b0c800";
      fetchSubmodules = true;
      sha256 = "sha256-bVCwc/2rPEZRLaZL6/XxK9zRQ1lyBSHAf49Y7b19UOs=";
    });
    date = "2022-11-24";
  };
  zeek-netmap = {
    pname = "zeek-netmap";
    version = "9a4d77d0ecd71c72b4e27579dc68c753139ae2c8";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek-netmap";
      rev = "9a4d77d0ecd71c72b4e27579dc68c753139ae2c8";
      fetchSubmodules = false;
      sha256 = "sha256-yObo/IFaPVwSkprCjL1ehjU3HS+PqmjN2cuXf6bQDl4=";
    });
    date = "2022-06-07";
  };
  zeek-postgresql = {
    pname = "zeek-postgresql";
    version = "b2b70900a3b4779efbcb9a39eae8cab1d714f97f";
    src = fetchFromGitHub ({
      owner = "0xxon";
      repo = "zeek-postgresql";
      rev = "b2b70900a3b4779efbcb9a39eae8cab1d714f97f";
      fetchSubmodules = false;
      sha256 = "sha256-O2yWL2Ippv5GFxSesv7Eclw78p2YnT3UWnZ8W54NMdc=";
    });
    date = "2022-07-06";
  };
  zeek-release = {
    pname = "zeek-release";
    version = "v5.0.4";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "zeek";
      rev = "v5.0.4";
      fetchSubmodules = true;
      sha256 = "sha256-XEfD6FF1gqEv8X1txulX1BTVqYKGEu3w3Tb+36ZwF0k=";
    });
  };
  zeek-spicy = {
    pname = "zeek-spicy";
    version = "f575c23cb2df602713f0b403555a420143e1c296";
    src = fetchFromGitHub ({
      owner = "zeek";
      repo = "spicy-plugin";
      rev = "f575c23cb2df602713f0b403555a420143e1c296";
      fetchSubmodules = false;
      sha256 = "sha256-AjvKVS6R496hMAQFkK4XI+6V2ZaHdQO31le351bOzxk=";
    });
    date = "2022-11-07";
  };
  zeek-tls = {
    pname = "zeek-tls";
    version = "5.1.1";
    src = fetchurl {
      url = "https://github.com/zeek/zeek/archive/refs/tags/v5.1.1.tar.gz";
      sha256 = "sha256-VTDF7tFdfFZDJDwXxclmF9sS0CpJL8Wn3D3FfjGO1tA=";
    };
  };
  zeek-xdp_packet = {
    pname = "zeek-xdp_packet";
    version = "a550256ba92cbddff392fbb01cf8fcbe6e945850";
    src = fetchFromGitHub ({
      owner = "0xxon";
      repo = "zeek-xdp_packet-plugin";
      rev = "a550256ba92cbddff392fbb01cf8fcbe6e945850";
      fetchSubmodules = false;
      sha256 = "sha256-ghDDSCAxaiaDuygJemGUm1Uq+aKac2MNc2dW84i7qSo=";
    });
    date = "2021-04-27";
  };
}
