# nvfetcher.toml
[zeek-latest]
src.git = "https://github.com/zeek/zeek"
fetch.github = "zeek/zeek"
git.fetchSubmodules = true

[zeek-release]
src.github_tag = "zeek/zeek"
src.include_regex = "v5.0.*"
fetch.github = "zeek/zeek"
git.fetchSubmodules = true

[zeek-tls]
src.github = "zeek/zeek"
fetch.url = "https://github.com/zeek/zeek/archive/refs/tags/v$ver.tar.gz"
src.prefix = "v"

[zeek-af_packet]
src.git = "https://github.com/J-Gras/zeek-af_packet-plugin"
fetch.github = "J-Gras/zeek-af_packet-plugin"

[zeek-xdp_packet]
src.git = "https://github.com/0xxon/zeek-xdp_packet-plugin"
fetch.github = "0xxon/zeek-xdp_packet-plugin"

[zeek-ikev2]
src.git = "https://github.com/ukncsc/zeek-ikev2"
fetch.github = "ukncsc/zeek-ikev2"

[zeek-postgresql]
src.git = "https://github.com/0xxon/zeek-postgresql"
fetch.github = "0xxon/zeek-postgresql"

[zeek-http2]
src.git = "https://github.com/MITRECND/bro-http2"
fetch.github = "MITRECND/bro-http2"

[zeek-community-id]
src.git = "https://github.com/corelight/zeek-community-id"
fetch.github = "corelight/zeek-community-id"

[zeek-netmap]
src.git = "https://github.com/zeek/zeek-netmap"
fetch.github = "zeek/zeek-netmap"

[netmap]
src.git = "https://github.com/luigirizzo/netmap"
fetch.github = "luigirizzo/netmap"

[icsnpp-bacnet]
src.git = "https://github.com/cisagov/icsnpp-bacnet"
fetch.github = "cisagov/icsnpp-bacnet"

[zeek-kafka]
src.git = "https://github.com/SeisoLLC/zeek-kafka"
fetch.github = "SeisoLLC/zeek-kafka"

[zeek-spicy]
#src.manual = "073b94bc4f49c1920e7f0f78075e10160cadcbc1"
src.git = "https://github.com/zeek/spicy-plugin"
fetch.github = "zeek/spicy-plugin"

[zeek-agent]
src.git = "https://github.com/zeek/zeek-agent"
fetch.github = "zeek/zeek-agent"
git.fetchSubmodules = true
