name: "CI"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 * 1,7,14,21,28 * *"
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v14
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210823_af94b54/install
        extra_nix_config: |
          experimental-features = nix-command flakes
          system-features = nixos-test benchmark big-parallel kvm recursive-nix
          extra-substituters = https://zeek.cachix.org
          extra-trusted-public-keys = zeek.cachix.org-1:pI1yRThH7gSh0ty7WmMWXqYFYigjcXFwiGiaaMmVpfA=

    - name: Run nvfetcher
      run: nix -Lv develop --command nvfetcher -l changelog

    - name: Check Spicy2nix Latest Rev
      run: nix flake lock --update-input spicy2nix

    - name: Build Zeek Release
      run: nix -Lv build ./#zeek-release

    - name: Check Zeek Plugins
      run: nix -Lv run .#zeek-release -- -N

    - name: Check Zeek Release Version
      run: nix -Lv run .#zeek-release -- --version

    - name: Check Spicy
      run: |
        nix -Lv run .#zeek-release -- -NN _Zeek::Spicy
        nix -Lv run .#spicyz -- -D zeek misc/my-http.spicy misc/my-http.evt -o misc/my-http.hlto

    - name: Check Zeek Systemd stand-alone module
      run: nix -Lv build ./#zeek-standalone-vm-systemd

    - name: Check Zeek Systemd Cluster module
      run: nix -Lv build ./#zeek-cluster-vm-systemd

    - name: COMMIT_MSG
      run: |
        changlog=$(find . -type f -name "changelog")
        if [[ ! -z "$(cat $changlog)" ]]; then
        echo "COMMIT_MSG<<EOF" >>$GITHUB_ENV
        echo "$(cat $changlog)" >>$GITHUB_ENV
        echo "EOF" >>$GITHUB_ENV
        rm -rf $changlog
        else
        rm -rf $changlog
        fi

    - name: Commit changes
      if: ${{ env.COMMIT_MSG != null }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ env.COMMIT_MSG }}
