name: "CI"
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20211228_ed3bc63/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix
            extra-substituters = https://zeek.cachix.org
            extra-trusted-public-keys = zeek.cachix.org-1:Jv0hB/P5eF7RQUZgSQiVqzqzgweP29YIwpSiukGlDWQ=

      - name: Run Nvfetcher Updates
        run: nix -Lv develop github:hardenedlinux/nixpkgs-hardenedlinux -c update nvfetcher ./nix/sources.toml

      - name: Check Spicy2nix Latest Rev
        run: nix flake lock --update-input spicy2nix

      - name: Build Zeek Release
        run: nix -Lv build ./#zeek-release

      - name: Check Zeek Plugins
        run: nix -Lv run .#zeek-release -- -N

      - name: Check Zeek Release Version
        run: nix -Lv run .#zeek-release -- --version

      - name: Check Spicy
        run: |
          nix -Lv run .#zeek-release -- -NN _Zeek::Spicy
          nix -Lv run .#spicyz -- -D zeek misc/my-http.spicy misc/my-http.evt -o misc/my-http.hlto

      - name: Build Zeek Micro-vm
        run: nix -Lv build ./#zeek-microvm

      - name: Check Zeek Systemd stand-alone module
        run: nix -Lv build ./#zeek-standalone-vm-systemd

      - name: Check Zeek Systemd Cluster module
        run: nix -Lv build ./#zeek-cluster-vm-systemd

      - name: Commit changes
        if: ${{ env.COMMIT_MSG != null }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.COMMIT_MSG }}
