name: "CI"
on:
  push:
    branches:
      - main
      - trying
      - staging
  schedule:
    - cron: "0 0 * * SUN" # every sunday
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v17
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.10.0pre20220629_b7eb4ac/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            system-features = nixos-test benchmark big-parallel kvm recursive-nix
            extra-substituters = https://zeek.cachix.org
            extra-trusted-public-keys = zeek.cachix.org-1:Jv0hB/P5eF7RQUZgSQiVqzqzgweP29YIwpSiukGlDWQ=

      - name: Run Nvfetcher Updates
        run: nix -Lv develop -c nvfetcher-update ./nix/sources.toml

      - name: Check Spicy2nix Latest Rev
        run: nix flake lock --update-input spicy2nix

      - name: Build Zeek Release
        run: nix -Lv build ./#zeek-release

      - name: Check Zeek Plugins
        run: nix -Lv run .#zeek-release -- -N

      - name: Check Zeek Release Version
        run: nix -Lv run .#zeek-release -- --version

      - name: Check Spicy
        run: nix develop -c nix -Lv run .#x86_64-linux.zeek.entrypoints.spicyCheck

      - name: Check Zeek Systemd stand-alone module
        run: nix -Lv build ./#zeek-standalone-vm-systemd

      # - name: Check Zeek Systemd Cluster module
      #   run: nix -Lv build ./#zeek-cluster-vm-systemd

      - name: Commit changes
        if: ${{ env.COMMIT_MSG != null }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ env.COMMIT_MSG }}
